spring:
  application:
    name: coupon
  jpa:
    open-in-view: false  # 트랜잭션 범위 외 지연 로딩 방지 (OSIV 비활성화)


snowflake:
  epoch: 1749826800000 #2025-06-13T15:00:00Z (UTC)
  node-id: 1
  timeout-ms: 5000
  max-attempts: 1000
